In [2]:
import numpy as np

In [3]:
arr = np.arange(1, 24, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [4]:
arr = np.linspace(5, 45, 9)

print(arr)
print(arr[1] - arr[0])

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
5.0


In [5]:
a = np.arange(1, 10)
b = np.linspace(1, 9, 9)

print(a)
print(b)

print(a.dtype)
print(b.dtype)

[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
int64
float64


In [6]:
arr = np.eye(6, dtype=int)
print(arr)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [7]:
arr = np.full((3, 4), 5)

print(arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("ndim:", arr.ndim)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape: (3, 4)
Size: 12
ndim: 2


In [8]:
a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])

print(a.dtype)
print(b.dtype)

b = b.astype(int)

print(a.dtype)
print(b.dtype)

int64
float64
int64
int64


In [9]:
np.array([10.9, 25.5, 39.99]).astype(int)

array([10, 25, 39])

In [11]:
arr = np.arange(10, 101, 10)

print(arr)

# (a) 4th element 
print(arr[3])
# (b) last element => 100
print(arr[-1])
# (c) 2nd last element -> 90
print(arr[-2])

[ 10  20  30  40  50  60  70  80  90 100]
40
100
90


In [12]:
#9. (a) 
print(arr[2:6])
# (b)
print(arr[::-1])



[30 40 50 60]
[100  90  80  70  60  50  40  30  20  10]


In [13]:
arr = np.arange(1, 21)

print(arr[1::3])

[ 2  5  8 11 14 17 20]


In [14]:
arr = np.arange(1, 21)

print(arr[2:-2])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
