In [2]:
! pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 4.8 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [175]:
import numpy as np



In [10]:
x = np.array([2,3,4,5])
x1 = np.array([2,3], [4,5], [8,9])
print(x.dtype)
print(x)
print(type(x))
print(x1)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [17]:
#print(np.zeros(20))
#print(np.zeros(10,dtype='int32'))
#print(np.zeros(3,4),dtype='int16')

print(np.ones(10))
print(np.ones((2,3,4)))
print(np.ones((2,2,3,4)))
print(np.ones((5,4)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
print(np.full((3,4),15))

[[15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]]


In [21]:
print(np.arange(10,5,-2))
print(np.arange(10))

[10  8  6]
[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(np.arange(1,11))
print(np.arange(1,11).reshape(2,5))
print(np.arange(1,13).reshape(4,3))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
print(np.linspace(1,10,5))
print(np.linspace(0,1,5))

[ 1.    3.25  5.5   7.75 10.  ]
[0.   0.25 0.5  0.75 1.  ]


In [30]:
print(np.eye(4))
print(np.eye(3,4))
print(np.eye(3,4,k=2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


Array Attribute

In [33]:
arr = np.arange(5)
arr.shape

(5,)

In [40]:
x = np.arange(20).reshape(4,5)
print(x)
print(x.shape)

print(arr.ndim)
print(x.ndim)
print(arr.size)
print(x.size)
print(len(arr))
print(len(x))


print(type(arr))
print(arr.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
1
2
5
20
5
4
<class 'numpy.ndarray'>
int64


In [41]:
#Question1
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [45]:
#Question2
print(np.zeros(3,3,3))
print(np.ones(3,3,3))

TypeError: Cannot interpret '3' as a data type

In [46]:
#Question3
print(np.arange(2,21,2))

[ 2  4  6  8 10 12 14 16 18 20]


In [49]:
arr = np.arange(10)
print(arr)
print(arr[-3:-12:-2])

[0 1 2 3 4 5 6 7 8 9]
[7 5 3 1]


In [53]:
arr = np.arange(20).reshape(5,4)
print(arr)
print(arr[2,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
10


In [72]:
print(arr)
print(arr[2:,1:])
print(arr[1,1:])
print(arr[::4,::3])
print(arr[1,1:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 9 10 11]
 [13 14 15]
 [17 18 19]]
[5 6 7]
[[ 0  3]
 [16 19]]
[5 6 7]


In [64]:
print(arr[1:3,2::-1])

[[ 6  5  4]
 [10  9  8]]


In [65]:
x = np.array([1,4,4.3,4.9,4.8],dtype='int32')
print(x)

[1 4 4 4 4]


In [67]:
x = np.array([1,4,4.3,4.9,4.8])
print(x)
print(x.astype('int32'))
print(x)

[1.  4.  4.3 4.9 4.8]
[1 4 4 4 4]
[1.  4.  4.3 4.9 4.8]


# Next Class 

In [76]:
arr1 = np.arange(10)
print(arr1)
arr1 = arr1+5
print("Multiply",arr1*5)
print(arr1)

print("exponent",arr1**2)

[0 1 2 3 4 5 6 7 8 9]
Multiply [25 30 35 40 45 50 55 60 65 70]
[ 5  6  7  8  9 10 11 12 13 14]
exponent [ 25  36  49  64  81 100 121 144 169 196]


In [79]:
x = np.arange(10)
y = np.arange(11,21)
print(x)
print(y)
print(x+y)
print(x*y)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[11 13 15 17 19 21 23 25 27 29]
[  0  12  26  42  60  80 102 126 152 180]


In [ ]:
x = np.arange(6).reshape(2,3)
y = np.arange(3).reshape(2,3)
print("x is",x)
print("y is",y)
print(" ")
print(x+y)

x is [[0 1 2]
 [3 4 5]]
y is [[0 1 2]]
 
[[0 2 4]
 [3 5 7]]


In [ ]:
x = np.arange(6).reshape(2,3)
y = np.arange(6).reshape(3,2)
print("x is",x)
print("y is",y)
print(" ")
print(x+y)

# check the error it is showing

x is [[0 1 2]
 [3 4 5]]
y is [[0 1]
 [2 3]
 [4 5]]
 


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [90]:
x = np.arange(5)
y = np.arange(1,6)
print(x)
print(y)
print(x==y)
print(x>y)
print(y>x)

[0 1 2 3 4]
[1 2 3 4 5]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]


In [ ]:
arr = np.array([3,4,5,10,25,56,7,8])
print(arr[])

# slicing ke through choose karne waala...upar karwa diya tha...maine chor nahi rakha

The np.random Module

In [107]:
np.random.seed(42)
np.random.rand(5)
# no matter how many times u run it...it will generate a new random value everytime - np.random.rand()
# agar seed likh diya to bhi random value hi dega but seed dene se vo har baar change nahi hogi
# range of seed 1 se leke 2 to the power 32




array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [106]:
np.random.randn(10)

array([-0.42804606, -0.74240684, -0.7033438 , -2.13962066, -0.62947496,
        0.59772047,  2.55948803,  0.39423302,  0.12221917, -0.51543566])

In [113]:
np.random.randint(10)


4

In [111]:
np.random.randint(10,20,5)

array([15, 14, 11, 17, 15])

In [114]:
np.random.randint(10,20,size=(5,3))

array([[10, 19, 15],
       [18, 10, 19],
       [12, 16, 13],
       [18, 12, 14],
       [12, 16, 14]])

In [115]:
lst = [3,4,56,7,9]
np.random.choice(lst,3)

array([3, 4, 7])

In [116]:
lst = [3,4,56,7,9]
np.random.choice(lst,3,replace=False)

array([ 9, 56,  4])

In [ ]:
lst = [3,4,56,7,9]
np.random.choice(lst,3,replace=False)
np.random.choice(10,5,replace=False)

array([1, 3, 6, 7, 2])

In [118]:
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[2 9 4 6 5 7 8 1 3 0]


In [129]:
# question 1
np.random.seed(42)
np.random.randint(1,7,10)

array([4, 5, 3, 5, 5, 2, 3, 3, 3, 5])

In [ ]:
# QUestion2
np.random.randint(35,100,20)


array([58, 37, 56, 87, 36, 64, 72, 36, 98, 94, 55, 67, 92, 56, 83, 93, 76,
       94, 49, 96])

In [134]:
arr = np.arange(6).reshape(2,3)
print(arr)
print("min",arr.min())
print("row min",arr.min(axis=1))
print("col min",arr.min(axis=0))

print("sum of the arr",arr.sum())
print("sum of the row",arr.sum(axis=1))
print(np.median(arr))
print(np.median(arr,axis=0))

[[0 1 2]
 [3 4 5]]
min 0
row min [0 3]
col min [0 1 2]
sum of the arr 15
sum of the row [ 3 12]
2.5
[1.5 2.5 3.5]


# Next Class

In [ ]:
arr = np.arange(24).reshape(3,4,2)
arr1 = np.arange(12).reshape(3,4)
print(arr*arr1)

ValueError: operands could not be broadcast together with shapes (3,4,2) (1,3,4) 

In [ ]:
arr = np.arange(12).reshape(4,-1)
print(arr)
print(arr.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [142]:
arr = np.arange(10)
print(arr.shape)
arr1= arr.reshape(1,-1) # row vector ban gaya
arr2 = arr.reshape(-1,1) #col vector bana diya
print("row vector", arr1)
print("col vector", arr2)

(10,)
row vector [[0 1 2 3 4 5 6 7 8 9]]
col vector [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [143]:
arr1 = np.arange(12)
arr1 = arr1[:,np.newaxis]
print(arr1.shape)

(12, 1)


In [146]:
arr =np.arange(12).reshape(4,3)
print(arr)
arr1 = arr.ravel() #shallow copy bana raha hai
arr1[0]= 99
arr2 = arr.flatten() #deep copy
arr1[1]= 100
print("original array",arr1)
print("flatten array",arr2)

print("ravel array",arr1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
original array [ 99 100   2   3   4   5   6   7   8   9  10  11]
flatten array [99  1  2  3  4  5  6  7  8  9 10 11]
ravel array [ 99 100   2   3   4   5   6   7   8   9  10  11]


In [150]:
# Question 1

arr = np.ones((3,4),dtype='int32')
arr1 = np.arange(10,31,10).reshape(3,1)
print(arr+arr1)

[[11 11 11 11]
 [21 21 21 21]
 [31 31 31 31]]


In [152]:
arr1 = np.array([[1,3,4],[2,3,5]])
arr2 = np.array([[5,6,7],[8,9,10],[10,11,12]])
arr4 = np.array(12).reshape(2,6)
print(arr1)
print(arr2)
arr3 = np.vstack((arr1,arr2))

print(np.hstack(arr1,arr4))
print(arr3)




ValueError: cannot reshape array of size 1 into shape (2,6)

In [155]:
# np.concatenate() with axis
# axis -> 0 vstack
# axis -> 1 hstack
print(arr1)
print(arr4)
np.concatenate((arr4,arr1),axis=1)
np.concatenate((arr2,arr1),axis=0)

[[1 3 4]
 [2 3 5]]


NameError: name 'arr4' is not defined

In [162]:
arr = np.array([2,-10,20,15,-10,10])
arr1 = np.where(arr<0,0,arr)
print(arr1)
print(arr)
arr2 = np.array([20,40,55,75,80,35])
arr3 = np.where(arr2<=40,"fail","pass")
print(arr3)


[ 2  0 20 15  0 10]
[  2 -10  20  15 -10  10]
['fail' 'fail' 'pass' 'pass' 'pass' 'fail']


In [ ]:
arr = np.array 

# Next Class

In [163]:
marks = np.array([35,68,42,91,27,55])
print(np.where(marks>50,'pass','fail'))

['fail' 'pass' 'fail' 'pass' 'fail' 'pass']


In [ ]:
# marks>=50 before >=70

marks = np.array([35,68,42,91,27,55])
print(np.where(marks>=50),'A',np.where(marks>=70),'B',np.where(marks<70),'')

In [172]:
marks = np.array([35,68,42,91,27,55])
grades = np.where(marks>= 75, 'A',
                  np.where(marks>=50),'B','C')
print(marks)
print(grades)

TypeError: where() takes from 1 to 3 positional arguments but 5 were given

In [ ]:
marks = np.array([36,68,42,91,27,55])
idx = np.where 

In [171]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[3,5],[5,6],[7,8]])
print(x)
print(x.T)
print(x@x.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


In [177]:
s1 = [72, 85, 60, 91]
s2 = [1, 2, 3, 4, 5]
s3 =[88, 66, 74, 100]

old = np.array([['62','71','55','80'],
                ['49','58','66','73']])

In [ ]:
table = np.array([s1,s2,s3])
print(table)
print(f"np of students{table.shape[0]} no of subject {table.shape[1]}")

print("total no of marks entires",table.size)
old = old.astype('int32')
print(np.sum(old,axis=1))
print(table.astype(float))
print()



ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.